name: Build and Deploy to Baota

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build

      - name: Deploy to Baota via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 134.175.73.246:4399
          username: JFK52nFdKP1E
          password: hpfddWfPTPKs
          local-dir: ./dist/
          server-dir: /www/wwwroot/test.potatom.top